# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43654280ed2ff412ea231c57cc6a996c4a1b07b47a93c05021a926ee297f2ca4b67ce156c7862ac65862f1591fc839b7db7da55392c8f4b3e22bf1528e1abf79

test:
  secret_key_base: 388193e60afcf8f26b43b9d7373ef11d3b872ea6b4a3e192844e14e17ce68494c45bbd5467e190055acab95c93b87b3d11447d6b7e899cb97108c5e9a446369a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
